#1 - Testing Repository with bug.
veeko21/student pull request #2
Opened 2021-08-25 15:44 UTC by veeko21

2021-08-25 15:50 UTC, emprestes requested changes

2021-08-25 15:50 UTC, emprestes commented on src/main/java/com/example/demo/student/Student.java
>      private int age;
A transient age? Why not provide a method to calculate the age base on dob field?

2021-08-25 15:50 UTC, emprestes commented on src/main/java/com/example/demo/student/StudentService.java
> +        return studentRepository.findAll();//this returns a list to us
👍🏽

2021-08-25 15:53 UTC, emprestes requested changes

2021-08-25 15:53 UTC, emprestes commented on src/main/java/com/example/demo/student/StudentRepository.java
> +    @Query("SELECT s FROM Student s WHERE s.email = ?1")
`:email` should be better than `?1`

2021-09-06 07:29 UTC, emprestes approved these changes
Good job!

2021-09-06 07:45 UTC, emprestes commented on src/main/java/com/example/demo/student/Student.java
>      private int age;
` pubilc int getAge() { // logic to calculate the age here base on dob field } `

2021-09-06 07:50 UTC, veeko21 commented on src/main/java/com/example/demo/student/Student.java
>      private int age;
public int getAge() {
        return Period.between(this.dob, LocalDate.now()).getYears();
 }

2021-09-06 07:59 UTC, merged